version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '8080:8080'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/app
    restart: 'unless-stopped'
    networks:
      - backend
    depends_on:
      - mongo
      - frontend
      - server

  server:
    build:
      context: ./
      dockerfile: Dockerfile.server
    container_name: server
    ports:
      - '3000:3000'
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: mongoose
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - mongo
    depends_on:
      - mongo

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    container_name: frontend
    volumes:
      - ./frontend:/app

  mongo:
    image: mvertes/alpine-mongo
    container_name: mongo
    env_file:
      - ./backend/.env
    ports:
      - '27017:27017'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
